function [solution] = SolveLCQPow0(casadi_formulation)

% Solver settings
params = GetLCQPowSettings("default", casadi_formulation);
params.qpSolver = 0;

% Get the LCQP formulation
problem = ObtainLCQPFromCasadi(casadi_formulation, params.qpSolver);

tic;
[solution.x,solution.y,solution.stats] = LCQPow(...
    problem.Q, ...
    problem.g, ...
    problem.L, ...
    problem.R, ...
    problem.lbL, ...
    problem.ubL, ...
    problem.lbR, ...
    problem.ubR, ...
    problem.A, ...
    problem.lbA, ...
    problem.ubA, ...
    problem.lb, ...
    problem.ub, ...
    params ...
);

solution.stats.elapsed_time_w_overhead = toc;

solution.stats.obj = full(problem.Obj(solution.x));
solution.stats.compl = full(problem.Phi(solution.x));

end

