function [solution] = SolveLCQPow0(casadi_formulation)

% Solver settings
params = GetLCQPowSettings("default", casadi_formulation);
params.qpSolver = 0;

problem = ObtainLCQPFromCasadi(casadi_formulation, params.qpSolver);

tic;

[solution.x,solution.y,solution.stats] = LCQPow(...
    problem.Q, ...
    problem.g, ...
    problem.L, ...
    problem.R, ...
    problem.lbL, ...
    problem.ubL, ...
    problem.lbR, ...
    problem.ubR, ...
    problem.A, ...
    problem.lbA, ...
    problem.ubA, ...
    problem.lb, ...
    problem.ub, ...
    params ...
);
solution.stats.elapsed_time_w_overhead = toc;
solution.stats.obj = full(problem.Obj(solution.x));
solution.stats.compl = full(problem.Phi(solution.x));

% TODO(jonas): Figure out why some of these are no longer working
if solution.stats.exit_flag ~= 0
    disp(solution.stats.qp_exit_flag)
    disp("Help");
end

end

