
run("MacMPECMatlab/bard1.m");

problem = ObtainLCQPFromCasadi(problem);

params.qpSolver = 0;
params.initialPenaltyParameter = 10e-9;

if params.qpSolver > 0
    problem.Q = sparse(problem.Q);
    problem.A = sparse(problem.A);
    problem.L = sparse(problem.L);
    problem.R = sparse(problem.R);
end

problem.A = [problem.A; 1 0 0 0 0; 0 1 0 0 0];
problem.lbA = [problem.lbA; 0; 0];
problem.ubA = [problem.ubA; inf; inf];

x = LCQPow( ...
    problem.Q, ...
    problem.g, ...
    problem.L, ...
    problem.R, ...
    problem.lbL, ...
    [], ...
    problem.lbR, ...
    [], ...
    problem.A, ...
    problem.lbA, ...
    problem.ubA, ...
    params ...
);
